language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
r_github_packages:
- leeper/prediction
r_packages:
- knitr
- rmarkdown
- testthat
- covr
- AER
- betareg
- ggplot2
- gapminder
- lme4
- nnet
- ordinal
- sandwich
- survey
- stargazer
after_success:
- R -q -e 'library("covr");codecov()'
